[theme]
# 1. 메인 색상: 요청하신 대로 형광색을 제외하고, 팔레트의 세련된 보라색으로 변경했습니다.
primaryColor = "#8CABD9"

# 2. 전체 배경색: 가장 깔끔한 흰색 계열로 선택했습니다.
backgroundColor = "#fdfdfd"

# 3. 보조 배경색: 메인 색상과 어울리는 연한 라벤더 색상입니다.
secondaryBackgroundColor = "#dabaff"

# 4. 글자색: 가독성을 위해 진한 남색을 선택했습니다.
textColor = "#0000a0"

# 폰트
font = "sans serif"